"""schema iniziale

Revision ID: 6f112c64bbd8
Revises:
Create Date: 2026-08-29 14:15:07.943007
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "6f112c64bbd8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("server", sa.String(length=255), nullable=False),
        sa.Column("export_path", sa.String(length=1024), nullable=False),
        sa.Column("mountpoint", sa.String(length=1024), nullable=False),
        sa.Column("nfs_version", sa.String(length=8), nullable=False),
        sa.Column(
            "requested_access",
            sa.Enum("SOLA_LETTURA", "LETTURA_SCRITTURA", name="accessonfs", native_enum=False),
            nullable=False,
        ),
        sa.Column("automount", sa.Boolean(), nullable=False),
        sa.Column("idle_timeout", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "CONFIGURATO", "MONTATO", "SMONTATO", "ERRORE", name="statomount", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("effective_read_write", sa.Boolean(), nullable=True),
        sa.Column("effective_options", sa.Text(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mountpoint"),
    )
    with op.batch_alter_table("mounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mounts_slug"), ["slug"], unique=True)

    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("scope", sa.String(length=1024), nullable=False),
        sa.Column("can_create", sa.Boolean(), nullable=False),
        sa.Column("can_delete", sa.Boolean(), nullable=False),
        sa.Column("can_modify", sa.Boolean(), nullable=False),
        sa.Column("can_rename", sa.Boolean(), nullable=False),
        sa.Column("can_share", sa.Boolean(), nullable=False),
        sa.Column("can_download", sa.Boolean(), nullable=False),
        sa.Column("can_upload", sa.Boolean(), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("theme", sa.String(length=16), nullable=False),
        sa.Column("hide_dotfiles", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "shares",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("mount_id", sa.Integer(), nullable=False),
        sa.Column("subpath", sa.String(length=1024), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "default_visibility",
            sa.Enum(
                "PUBBLICA", "PASSWORD", "UTENTI", "NEGATA", name="visibilita", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["mount_id"], ["mounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shares", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shares_slug"), ["slug"], unique=True)

    op.create_table(
        "access_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("share_id", sa.Integer(), nullable=False),
        sa.Column("path_prefix", sa.String(length=1024), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum(
                "PUBBLICA", "PASSWORD", "UTENTI", "NEGATA", name="visibilita", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["share_id"], ["shares.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "share_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("share_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_downloads", sa.Integer(), nullable=True),
        sa.Column("download_count", sa.Integer(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["share_id"], ["shares.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("share_links", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_share_links_token_hash"), ["token_hash"], unique=True)

    op.create_table(
        "vhosts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("path_prefix", sa.String(length=255), nullable=False),
        sa.Column("share_id", sa.Integer(), nullable=False),
        sa.Column(
            "webserver",
            sa.Enum("APACHE", "NGINX", name="webserver", native_enum=False),
            nullable=False,
        ),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("rendered_config", sa.Text(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["share_id"], ["shares.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("vhosts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vhosts_hostname"), ["hostname"], unique=False)

    op.create_table(
        "transfers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("DOWNLOAD", "UPLOAD", name="tipotrasferimento", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "IN_CORSO",
                "COMPLETATO",
                "INTERROTTO",
                "FALLITO",
                name="statotrasferimento",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("share_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("share_link_id", sa.Integer(), nullable=True),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("bytes_transferred", sa.Integer(), nullable=True),
        sa.Column("client_ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("is_resumed", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["share_id"], ["shares.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["share_link_id"], ["share_links.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transfers")
    with op.batch_alter_table("vhosts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vhosts_hostname"))

    op.drop_table("vhosts")
    with op.batch_alter_table("share_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_share_links_token_hash"))

    op.drop_table("share_links")
    op.drop_table("access_rules")
    with op.batch_alter_table("shares", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shares_slug"))

    op.drop_table("shares")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    op.drop_table("settings")
    with op.batch_alter_table("mounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mounts_slug"))

    op.drop_table("mounts")
    # ### end Alembic commands ###
