"""vhost non legato a una sola pubblicazione

Revision ID: 7bd9aecd96f7
Revises: fc574e85c4f4
Create Date: 2026-08-29 23:20:02.444129
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "7bd9aecd96f7"
down_revision: str | None = "fc574e85c4f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vhosts", schema=None) as batch_op:
        batch_op.alter_column("share_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vhosts", schema=None) as batch_op:
        batch_op.alter_column("share_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
