"""permessi per utente

Revision ID: fc574e85c4f4
Revises: 6f112c64bbd8
Create Date: 2026-08-29 18:54:05.125993
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fc574e85c4f4'
down_revision: str | None = '6f112c64bbd8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permessi_utente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('path_prefix', sa.String(length=1024), nullable=False),
    sa.Column('livello', sa.Enum('NEGATO', 'LETTURA', 'SCRITTURA', name='livello', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['share_id'], ['shares.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'share_id', 'path_prefix', name='uq_permesso_percorso')
    )
    with op.batch_alter_table('permessi_utente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permessi_utente_share_id'), ['share_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permessi_utente_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('access_rules', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PUBBLICA', 'PASSWORD', 'UTENTI', 'UTENTI_SCELTI', 'NEGATA', name='visibilita', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.alter_column('default_visibility',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PUBBLICA', 'PASSWORD', 'UTENTI', 'UTENTI_SCELTI', 'NEGATA', name='visibilita', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.alter_column('default_visibility',
               existing_type=sa.Enum('PUBBLICA', 'PASSWORD', 'UTENTI', 'UTENTI_SCELTI', 'NEGATA', name='visibilita', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    with op.batch_alter_table('access_rules', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.Enum('PUBBLICA', 'PASSWORD', 'UTENTI', 'UTENTI_SCELTI', 'NEGATA', name='visibilita', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    with op.batch_alter_table('permessi_utente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permessi_utente_user_id'))
        batch_op.drop_index(batch_op.f('ix_permessi_utente_share_id'))

    op.drop_table('permessi_utente')
    # ### end Alembic commands ###
